### ISSUE TITLE
Currently selected message no highlight

### ISSUE THREAD

**Issue by dmedinag** [jeremiecook/protonmail-theme#1]
The original theme shows you what message are you going to apply the keyboard shortcut to, this is lacking in the theme making it difficult to use the keyboard shortcuts. Images attached for before and after the action of pressing the arrow down (without pressing enter)

<img width="1280" alt="screen shot 2017-02-07 at 11 12 33" src="https://cloud.githubusercontent.com/assets/7140086/22706734/5fa8d108-ed3e-11e6-827a-bd465455bafa.png">
<img width="1280" alt="screen shot 2017-02-07 at 11 12 37" src="https://cloud.githubusercontent.com/assets/7140086/22706740/63c7de28-ed3e-11e6-96c2-66f7989817c2.png">

**Comment by jeremiecook** [comment]
It should be good, now !

**Comment by dmedinag** [comment]
Great job! Thank you
