### ISSUE TITLE
Font issue ?

### ISSUE THREAD

**Issue by Galiwyx** [jeremiecook/protonmail-theme#11]
Hello,

On Firefox 72, the font looks too small. Is it a bug ?

![image](https://user-images.githubusercontent.com/206181/73461504-8b475380-437a-11ea-98dc-fea8516069a4.png)

Thank you :)

**Comment by jeremiecook** [comment]
Hi there! On my mac (Firefox 73) it looks like just like the picture. It's actually a screenshot.
But I guess it depends on your screen resolution.

I should probably make the font size a variable you can tweak for your needs. I'll try to do it soon !

**Comment by Galiwyx** [comment]
Hi,

Ok, for me it's not the same as the screenshot (It looks thicker). My resolution is 2540x1440. 

Thank you for the font update ! (For me), the default font of ProtonMail is perfect.

**Comment by jeremiecook** [comment]
Just updated the css vars. You can now edit --message-font-size to 1.3 or 1.4rem depending on your needs.

**Comment by Galiwyx** [comment]
Perfect, thank you :)
